version: "3"
services:
  api:
    container_name: backend
    build: .
    ports:
      - "3333:3000"
    command: npm run dev
    volumes:
      - .:/home/app/
    links:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://cache
  mongo:
    container_name: mongoDB_dev
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: omnistack
      MONGO_INITDB_ROOT_PASSWORD: omnistack

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
